### ISSUE TITLE
ModuleNotFoundError: No module named 'genetic.population'

### ISSUE THREAD

**Issue by TyjChristy** [yn-sun/ea-cnn#5]
Traceback (most recent call last):
  File "evolve.py", line 1, in <module>
    from utils import StatusUpdateTool, Utils, Log
  File "/home/guohy/eacnn-sum/ea-cnn/utils.py", line 5, in <module>
    from genetic.population import Population, Individual, DenseUnit, ResUnit, PoolUnit
ModuleNotFoundError: No module named 'genetic.population'

Can you tell me how to solve the ModuleNotFound Problem? Thank you very much.

**Comment by lvxianlong** [comment]
Have you solved the problem?？？
